/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLembretesRouteImport } from './routes/_authenticated/lembretes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated/atendimentos'
import { Route as AuthenticatedConsulentesIndexRouteImport } from './routes/_authenticated/consulentes.index'
import { Route as AuthenticatedConsulentesIdRouteImport } from './routes/_authenticated/consulentes.$id'

const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLembretesRoute = AuthenticatedLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsulentesIndexRoute =
  AuthenticatedConsulentesIndexRouteImport.update({
    id: '/consulentes/',
    path: '/consulentes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsulentesIdRoute =
  AuthenticatedConsulentesIdRouteImport.update({
    id: '/consulentes/$id',
    path: '/consulentes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/consulentes/$id': typeof AuthenticatedConsulentesIdRoute
  '/consulentes/': typeof AuthenticatedConsulentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/consulentes/$id': typeof AuthenticatedConsulentesIdRoute
  '/consulentes': typeof AuthenticatedConsulentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lembretes': typeof AuthenticatedLembretesRoute
  '/_authenticated/consulentes/$id': typeof AuthenticatedConsulentesIdRoute
  '/_authenticated/consulentes/': typeof AuthenticatedConsulentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/atendimentos'
    | '/dashboard'
    | '/lembretes'
    | '/consulentes/$id'
    | '/consulentes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/atendimentos'
    | '/dashboard'
    | '/lembretes'
    | '/consulentes/$id'
    | '/consulentes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pending-approval'
    | '/_authenticated/atendimentos'
    | '/_authenticated/dashboard'
    | '/_authenticated/lembretes'
    | '/_authenticated/consulentes/$id'
    | '/_authenticated/consulentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lembretes': {
      id: '/_authenticated/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof AuthenticatedLembretesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consulentes/': {
      id: '/_authenticated/consulentes/'
      path: '/consulentes'
      fullPath: '/consulentes/'
      preLoaderRoute: typeof AuthenticatedConsulentesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consulentes/$id': {
      id: '/_authenticated/consulentes/$id'
      path: '/consulentes/$id'
      fullPath: '/consulentes/$id'
      preLoaderRoute: typeof AuthenticatedConsulentesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLembretesRoute: typeof AuthenticatedLembretesRoute
  AuthenticatedConsulentesIdRoute: typeof AuthenticatedConsulentesIdRoute
  AuthenticatedConsulentesIndexRoute: typeof AuthenticatedConsulentesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLembretesRoute: AuthenticatedLembretesRoute,
  AuthenticatedConsulentesIdRoute: AuthenticatedConsulentesIdRoute,
  AuthenticatedConsulentesIndexRoute: AuthenticatedConsulentesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
